package com.travelopedia.model;

import java.util.ArrayList;

class Data {

    public static void main(String[] args) {

        ArrayList flightList = new ArrayList();

        // open
        flightList.add(" TO SAN-San Diego, CA");
        flightList.add("SAN-San Diego, CA TO PHX-Phoenix,AZ");
        flightList.add("SAN-San Diego, CA TO DEN-Denver, CO");
        flightList.add("SAN-San Diego, CA TO IAD-Washington, DC");
        flightList.add("SAN-San Diego, CA TO MIA-Miami,FL");
        flightList.add("SAN-San Diego, CA TO SEA-Seattle,WA");
        flightList.add("SAN-San Diego, CA TO SFO-San Francisco,CA");
        flightList.add("SAN-San Diego, CA TO LGA-New York,NY");
        flightList.add("SAN-San Diego, CA TO ORF-Norfolk,VA");
        flightList.add("SAN-San Diego, CA TO CLE-Cleveland,OH");
        flightList.add("SAN-San Diego, CA TO LAX-Los Angeles,CA");
        flightList.add("SAN-San Diego, CA TO BUF-Buffalo,NY");
        flightList.add("SAN-San Diego, CA TO PHX-EWR-Newark,NJ");
        flightList.add("SAN-San Diego, CA TO MSP-Minneapolis,MN");
        flightList.add("PHX-Phoenix,AZ, CA TO SAN-San Diego");
        flightList.add("PHX-Phoenix,AZ, CA TO DEN-Denver, CO");
        flightList.add("PHX-Phoenix,AZ, CA TO IAD-Washington, DC");
        flightList.add("PHX-Phoenix,AZ, CA TO MIA-Miami,FL");
        flightList.add("PHX-Phoenix,AZ, CA TO SEA-Seattle,WA");
        flightList.add("PHX-Phoenix,AZ, CA TO SFO-San Francisco,CA");
        flightList.add("PHX-Phoenix,AZ, CA TO LGA-New York,NY");
        flightList.add("PHX-Phoenix,AZ, CA TO ORF-Norfolk,VA");
        flightList.add("PHX-Phoenix,AZ, CA TO CLE-Cleveland,OH");
        flightList.add("PHX-Phoenix,AZ, CA TO LAX-Los Angeles,CA");
        flightList.add("PHX-Phoenix,AZ, CA TO BUF-Buffalo,NY");
        flightList.add("PHX-Phoenix,AZ, CA TO PHX-EWR-Newark,NJ");
        flightList.add("PHX-Phoenix,AZ, CA TO MSP-Minneapolis,MN");
        flightList.add("DEN-Denver, CO, CA TO SAN-San Diego");
        flightList.add("DEN-Denver, CO, CA TO IAD-Washington, DC");
        flightList.add("DEN-Denver, CO, CA TO MIA-Miami,FL");
        flightList.add("DEN-Denver, CO, CA TO SEA-Seattle,WA");
        flightList.add("DEN-Denver, CO, CA TO SFO-San Francisco,CA");
        flightList.add("DEN-Denver, CO, CA TO LGA-New York,NY");
        flightList.add("DEN-Denver, CO, CA TO ORF-Norfolk,VA");
        flightList.add("DEN-Denver, CO, CA TO CLE-Cleveland,OH");
        flightList.add("DEN-Denver, CO, CA TO LAX-Los Angeles,CA");
        flightList.add("DEN-Denver, CO, CA TO BUF-Buffalo,NY");
        flightList.add("DEN-Denver, CO, CA TO PHX-EWR-Newark,NJ");
        flightList.add("DEN-Denver, CO, CA TO MSP-Minneapolis,MN");
        flightList.add("IAD-Washington, DC, CA TO PHX-Phoenix,AZ");
        flightList.add("IAD-Washington, DC TO DEN-Denver, CO");
        flightList.add("IAD-Washington, DC TO MIA-Miami,FL");
        flightList.add("IAD-Washington, DC TO SEA-Seattle,WA");
        flightList.add("IAD-Washington, DC TO SFO-San Francisco,CA");
        flightList.add("IAD-Washington, DC TO LGA-New York,NY");
        flightList.add("IAD-Washington, DC TO ORF-Norfolk,VA");
        flightList.add("IAD-Washington, DC TO CLE-Cleveland,OH");
        flightList.add("IAD-Washington, DC TO LAX-Los Angeles,CA");
        flightList.add("IAD-Washington, DC TO BUF-Buffalo,NY");
        flightList.add("IAD-Washington, DC TO PHX-EWR-Newark,NJ");
        flightList.add("IAD-Washington, DC TO MSP-Minneapolis,MN");
        flightList.add("IAD-Washington, DC TO SAN-San Diego, CA");
        flightList.add("MIA-Miami,FL TO PHX-Phoenix,AZ");
        flightList.add("MIA-Miami,FL TO DEN-Denver, CO");
        flightList.add("MIA-Miami,FL TO IAD-Washington, DC");
        flightList.add("MIA-Miami,FL TO SEA-Seattle,WA");
        flightList.add("MIA-Miami,FL TO SFO-San Francisco,CA");
        flightList.add("MIA-Miami,FL TO LGA-New York,NY");
        flightList.add("MIA-Miami,FL TO ORF-Norfolk,VA");
        flightList.add("MIA-Miami,FL TO CLE-Cleveland,OH");
        flightList.add("MIA-Miami,FL TO LAX-Los Angeles,CA");
        flightList.add("MIA-Miami,FL TO BUF-Buffalo,NY");
        flightList.add("MIA-Miami,FL TO PHX-EWR-Newark,NJ");
        flightList.add("MIA-Miami,FL TO MSP-Minneapolis,MN");
        flightList.add("MIA-Miami,FL TO SAN-San Diego, CA");
        flightList.add("SEA-Seattle,WA TO PHX-Phoenix,AZ");
        flightList.add("SEA-Seattle,WA TO DEN-Denver, CO");
        flightList.add("SEA-Seattle,WA TO IAD-Washington, DC");
        flightList.add("SEA-Seattle,WA TO MIA-Miami,FL");
        flightList.add("SEA-Seattle,WA TO SFO-San Francisco,CA");
        flightList.add("SEA-Seattle,WA TO LGA-New York,NY");
        flightList.add("SEA-Seattle,WA TO ORF-Norfolk,VA");
        flightList.add("SEA-Seattle,WA TO CLE-Cleveland,OH");
        flightList.add("SEA-Seattle,WA TO LAX-Los Angeles,CA");
        flightList.add("SEA-Seattle,WA TO BUF-Buffalo,NY");
        flightList.add("SEA-Seattle,WA TO PHX-EWR-Newark,NJ");
        flightList.add("SEA-Seattle,WA TO MSP-Minneapolis,MN");
        flightList.add("SEA-Seattle,WA TO SAN-San Diego, CA");
        flightList.add("SFO-San Francisco,CA TO PHX-Phoenix,AZ");
        flightList.add("SFO-San Francisco,CA TO DEN-Denver, CO");
        flightList.add("SFO-San Francisco,CA TO IAD-Washington, DC");
        flightList.add("SFO-San Francisco,CA TO MIA-Miami,FL");
        flightList.add("SFO-San Francisco,CA TO SEA-Seattle,WA");
        flightList.add("SFO-San Francisco,CA TO LGA-New York,NY");
        flightList.add("SFO-San Francisco,CA TO ORF-Norfolk,VA");
        flightList.add("SFO-San Francisco,CA TO CLE-Cleveland,OH");
        flightList.add("SFO-San Francisco,CA TO LAX-Los Angeles,CA");
        flightList.add("SFO-San Francisco,CA TO BUF-Buffalo,NY");
        flightList.add("SFO-San Francisco,CA TO PHX-EWR-Newark,NJ");
        flightList.add("SFO-San Francisco,CA TO MSP-Minneapolis,MN");
        flightList.add("SFO-San Francisco,CA TO SAN-San Diego, CA");
        flightList.add("LGA-New York,NY TO SAN-San Diego, CA");
        flightList.add("LGA-New York,NY TO PHX-Phoenix,AZ");
        flightList.add("LGA-New York,NY TO DEN-Denver, CO");
        flightList.add("LGA-New York,NY TO IAD-Washington, DC");
        flightList.add("LGA-New York,NY TO MIA-Miami,FL");
        flightList.add("LGA-New York,NY TO SEA-Seattle,WA");
        flightList.add("LGA-New York,NY TO SFO-San Francisco,CA");
        flightList.add("LGA-New York,NY TO ORF-Norfolk,VA");
        flightList.add("LGA-New York,NY TO CLE-Cleveland,OH");
        flightList.add("LGA-New York,NY TO LAX-Los Angeles,CA");
        flightList.add("LGA-New York,NY TO BUF-Buffalo,NY");
        flightList.add("LGA-New York,NY TO PHX-EWR-Newark,NJ");
        flightList.add("LGA-New York,NY TO MSP-Minneapolis,MN");
        flightList.add("ORF-Norfolk,VA TO SAN-San Diego, CA");
        flightList.add("ORF-Norfolk,VA TO PHX-Phoenix,AZ");
        flightList.add("ORF-Norfolk,VA TO DEN-Denver, CO");
        flightList.add("ORF-Norfolk,VA TO IAD-Washington, DC");
        flightList.add("ORF-Norfolk,VA TO MIA-Miami,FL");
        flightList.add("ORF-Norfolk,VA TO SEA-Seattle,WA");
        flightList.add("ORF-Norfolk,VA TO SFO-San Francisco,CA");
        flightList.add("ORF-Norfolk,VA TO LGA-New York,NY");
        flightList.add("ORF-Norfolk,VA TO CLE-Cleveland,OH");
        flightList.add("ORF-Norfolk,VA TO LAX-Los Angeles,CA");
        flightList.add("ORF-Norfolk,VA TO BUF-Buffalo,NY");
        flightList.add("ORF-Norfolk,VA TO PHX-EWR-Newark,NJ");
        flightList.add("ORF-Norfolk,VA TO MSP-Minneapolis,MN");
        flightList.add("CLE-Cleveland,OH TO SAN-San Diego, CA");
        flightList.add("CLE-Cleveland,OH TO PHX-Phoenix,AZ");
        flightList.add("CLE-Cleveland,OH TO DEN-Denver, CO");
        flightList.add("CLE-Cleveland,OH TO IAD-Washington, DC");
        flightList.add("CLE-Cleveland,OH TO MIA-Miami,FL");
        flightList.add("CLE-Cleveland,OH TO SEA-Seattle,WA");
        flightList.add("CLE-Cleveland,OH TO SFO-San Francisco,CA");
        flightList.add("CLE-Cleveland,OH TO LGA-New York,NY");
        flightList.add("CLE-Cleveland,OH TO ORF-Norfolk,VA");
        flightList.add("CLE-Cleveland,OH TO LAX-Los Angeles,CA");
        flightList.add("CLE-Cleveland,OH TO BUF-Buffalo,NY");
        flightList.add("CLE-Cleveland,OH TO PHX-EWR-Newark,NJ");
        flightList.add("CLE-Cleveland,OH TO MSP-Minneapolis,MN");
        flightList.add("Los Angeles,CA TO SAN-San Diego, CA");
        flightList.add("Los Angeles,CA TO PHX-Phoenix,AZ");
        flightList.add("Los Angeles,CA TO DEN-Denver, CO");
        flightList.add("Los Angeles,CA TO IAD-Washington, DC");
        flightList.add("Los Angeles,CA TO MIA-Miami,FL");
        flightList.add("Los Angeles,CA TO SEA-Seattle,WA");
        flightList.add("Los Angeles,CA TO SFO-San Francisco,CA");
        flightList.add("Los Angeles,CA TO LGA-New York,NY");
        flightList.add("Los Angeles,CA TO ORF-Norfolk,VA");
        flightList.add("Los Angeles,CA TO CLE-Cleveland,OH");
        flightList.add("Los Angeles,CA TO BUF-Buffalo,NY");
        flightList.add("Los Angeles,CA TO PHX-EWR-Newark,NJ");
        flightList.add("Los Angeles,CA TO MSP-Minneapolis,MN");
        flightList.add("BUF-Buffalo,NY TO SAN-San Diego, CA");
        flightList.add("BUF-Buffalo,NY TO PHX-Phoenix,AZ");
        flightList.add("BUF-Buffalo,NY TO DEN-Denver, CO");
        flightList.add("BUF-Buffalo,NY TO IAD-Washington, DC");
        flightList.add("BUF-Buffalo,NY TO MIA-Miami,FL");
        flightList.add("BUF-Buffalo,NY TO SEA-Seattle,WA");
        flightList.add("BUF-Buffalo,NY TO SFO-San Francisco,CA");
        flightList.add("BUF-Buffalo,NY TO LGA-New York,NY");
        flightList.add("BUF-Buffalo,NY TO ORF-Norfolk,VA");
        flightList.add("BUF-Buffalo,NY TO CLE-Cleveland,OH");
        flightList.add("BUF-Buffalo,NY TO LAX-Los Angeles,CA");
        flightList.add("BUF-Buffalo,NY TO PHX-EWR-Newark,NJ");
        flightList.add("BUF-Buffalo,NY TO MSP-Minneapolis,MN");
        flightList.add("EWR-Newark,NJ TO SAN-San Diego, CA");
        flightList.add("EWR-Newark,NJ TO PHX-Phoenix,AZ");
        flightList.add("EWR-Newark,NJ TO DEN-Denver, CO");
        flightList.add("EWR-Newark,NJ TO IAD-Washington, DC");
        flightList.add("EWR-Newark,NJ TO MIA-Miami,FL");
        flightList.add("EWR-Newark,NJ TO SEA-Seattle,WA");
        flightList.add("EWR-Newark,NJ TO SFO-San Francisco,CA");
        flightList.add("EWR-Newark,NJ TO LGA-New York,NY");
        flightList.add("EWR-Newark,NJ TO ORF-Norfolk,VA");
        flightList.add("EWR-Newark,NJ TO CLE-Cleveland,OH");
        flightList.add("EWR-Newark,NJ TO LAX-Los Angeles,CA");
        flightList.add("EWR-Newark,NJ TO BUF-Buffalo,NY");
        flightList.add("EWR-Newark,NJ TO MSP-Minneapolis,MN");
        flightList.add("MSP-Minneapolis,MN TO SAN-San Diego, CA");
        flightList.add("MSP-Minneapolis,MN TO PHX-Phoenix,AZ");
        flightList.add("MSP-Minneapolis,MN TO DEN-Denver, CO");
        flightList.add("MSP-Minneapolis,MN TO IAD-Washington, DC");
        flightList.add("MSP-Minneapolis,MN TO MIA-Miami,FL");
        flightList.add("MSP-Minneapolis,MN TO SEA-Seattle,WA");
        flightList.add("MSP-Minneapolis,MN TO SFO-San Francisco,CA");
        flightList.add("MSP-Minneapolis,MN TO LGA-New York,NY");
        flightList.add("MSP-Minneapolis,MN TO ORF-Norfolk,VA");
        flightList.add("MSP-Minneapolis,MN TO CLE-Cleveland,OH");
        flightList.add("MSP-Minneapolis,MN TO LAX-Los Angeles,CA");
        flightList.add("MSP-Minneapolis,MN TO BUF-Buffalo,NY");
        flightList.add("MSP-Minneapolis,MN TO PHX-EWR-Newark,NJ");


    }
}
